# Generated by Django 3.1.7 on 2022-05-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('priority',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
