# Generated by Django 3.1.7 on 2022-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_auto_20220501_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_for_cart',
            field=models.BooleanField(default=False, verbose_name='Категория "У кассы"'),
        ),
    ]
