# Generated by Django 3.1.7 on 2022-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0004_auto_20220502_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
