# Generated by Django 3.1.7 on 2022-05-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0005_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='nomenclature.Tag'),
        ),
    ]
