# Generated by Django 3.1.7 on 2022-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0006_items_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='nomenclature.Tag'),
        ),
    ]
