FROM python:3.8
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y gettext libgettextpo-dev

RUN mkdir -p /static /media

COPY ./requirements_correct.txt /requirements_correct.txt
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade -r /requirements_correct.txt

ADD . /barbar_food
WORKDIR /barbar_food

ENV WAIT_VERSION 2.7.2
ENV DJANGO_SETTINGS_MODULE=config.settings.development
ENV PORT 30001

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

COPY ./entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh

CMD ["/entrypoint.dev.sh"]