# Generated by Django 3.1.7 on 2022-05-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
