# Generated by Django 3.1.7 on 2022-05-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Дом / здание')),
                ('is_private_home', models.BooleanField(default=False, verbose_name='Частный дом')),
                ('entrance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Этаж')),
                ('flat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('cart', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
            ],
        ),
    ]
