# Generated by Django 3.1.7 on 2022-05-05 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220501_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
